domain: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nicolas Castellano Developer" # the name of your site, e.g. ACME Corp.
markdown: kramdown
collections:
  portfolio:
    permalink: /:collection/:name
    output: true
permalink: /blog/:year/:month/:day/:title
# sass:
#   sass_dir: _sass
#   style: compressed
# plugins:
#   - jekyll-coffeescript
# defaults:
#   - scope:
#       path: "assets/images"
#     values:
#       image: true
#   - scope:
#       path: "assets/js"
#     values:
#       js: true
#   - scope:
#       path: "assets/svg"
#     values:
#       svg: true
#   - scope:
#       path: "assets/css"
#     values:
#       css: true