domain: "nicolas-castellano.github.io"
url: "nicolas-castellano.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nicolas Castellano Developer" # the name of your site, e.g. ACME Corp.
markdown: kramdown
collections:
  portfolio:
    permalink: /:collection/:name
    output: true
permalink: /blog/:year/:month/:day/:title